# Generated by Django 5.0.1 on 2024-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_author_categories_contact_language_level_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
