# Generated by Django 4.2.4 on 2024-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='media/default.jpg', null=True, upload_to='media'),
        ),
    ]
