# Generated by Django 4.2.4 on 2024-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0007_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='/media/default.jpg', null=True, upload_to='media/'),
        ),
    ]
