# Generated by Django 4.2.4 on 2024-01-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0012_review_profile_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
