# Generated by Django 4.2.4 on 2024-01-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0013_remove_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, to='coder.course'),
        ),
    ]
