# Generated by Django 4.2.4 on 2024-01-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0018_certificates_delete_lessoncompletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
